# Generated by Django 3.1.1 on 2020-10-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together={('product_id', 'size_id', 'color_id')},
        ),
    ]
