# Generated by Django 3.1.1 on 2020-10-15 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
        ('product', '0002_auto_20201012_0535'),
    ]

    operations = [
    ]
