# Generated by Django 3.1.1 on 2020-10-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_20201015_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
