# Generated by Django 3.1.1 on 2020-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('pr_1', models.TextField()),
                ('pr_2', models.TextField()),
                ('pr_3', models.TextField()),
                ('img_1', models.TextField()),
                ('img_2', models.TextField()),
                ('img_3', models.TextField()),
            ],
        ),
    ]
