# Generated by Django 3.1.1 on 2020-11-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='shopping_carg_id',
        ),
        migrations.AddField(
            model_name='sell',
            name='code',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='method_pay',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='shopping_car_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.shoppingcart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statussell',
            name='state',
            field=models.IntegerField(),
        ),
    ]
